// Logical IDs from the constitution §3 selector contract. Centralized so the exact strings
// the harness selects on live in one place and can't drift.
export const IDS = {
  screenLogin: 'screen_login',
  loginGoogleButton: 'login_google_button',
  loginErrorMessage: 'login_error_message',
  screenHome: 'screen_home',
  videoList: 'video_list',
  videoListItem: 'video_list_item',
  videoCount: 'video_count',
  overflowMenuButton: 'overflow_menu_button',
  logoutButton: 'logout_button',
  refreshControl: 'refresh_control',
  filterButton: 'filter_button',
  filterApplyButton: 'filter_apply_button',
  sortButton: 'sort_button',
  sortApplyButton: 'sort_apply_button',
  mapNavButton: 'map_nav_button',
  screenMap: 'screen_map',
  mapMarker: 'map_marker',
  detailBottomSheet: 'detail_bottom_sheet',
  detailVideoUrl: 'detail_video_url',
  detailOpenYoutubeButton: 'detail_open_youtube_button',
  loadingIndicator: 'loading_indicator',
  errorView: 'error_view',
  errorRetryButton: 'error_retry_button',
  externalOpenUrl: 'external_open_url',
  externalOpenError: 'external_open_error',
} as const;
